# Generated by Django 3.0.8 on 2021-07-22 02:38

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AGPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('author', models.CharField(default='Stephen Busic', max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('desc', ckeditor.fields.RichTextField(max_length=750)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('has_sources', models.BooleanField(default=True)),
                ('sources', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('type', models.CharField(max_length=160)),
                ('date', models.DateField(auto_now_add=True)),
                ('thumb', models.ImageField(blank=True, default='default_thumb.jpg', upload_to=posts.models.generate_imagepath)),
                ('square_thumb', models.ImageField(blank=True, default='default_square_thumb.jpg', upload_to=posts.models.generate_imagepath)),
                ('email_subs', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('ref_number', models.IntegerField(default=posts.models.create_new_ref_number)),
            ],
            options={
                'verbose_name_plural': 'AGPosts',
                'ordering': ['-date'],
                'permissions': [('can_comment_or_reply', 'Can create comments or replies')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=4000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deactivated_on', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notify', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=10)),
                ('pinned', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('agpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.AGPost')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agpost'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=4000)),
                ('handle', models.CharField(blank=True, default='', max_length=90)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deactivated_on', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notify', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=10)),
                ('pinned', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.Comment')),
            ],
            options={
                'verbose_name_plural': 'Replies',
                'ordering': ['comment', 'rank', 'created_on'],
            },
        ),
    ]
