# Generated by Django 3.0.8 on 2021-02-23 03:00

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('author', models.CharField(default='Stephen Busic', max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('desc', ckeditor.fields.RichTextField(max_length=750)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('has_sources', models.BooleanField(default=True)),
                ('sources', ckeditor_uploader.fields.RichTextUploadingField()),
                ('type', models.CharField(max_length=160)),
                ('date', models.DateField(auto_now_add=True)),
                ('thumb', models.ImageField(blank=True, default='default_thumb.jpg', upload_to=posts.models.generate_imagepath)),
                ('square_thumb', models.ImageField(blank=True, default='default_square_thumb.jpg', upload_to=posts.models.generate_imagepath)),
                ('email_subs', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'AGPosts',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField(max_length=4000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('notify', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=10)),
                ('pinned', models.BooleanField(default=False)),
                ('agpost', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.AGPost')),
            ],
            options={
                'ordering': ['rank', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField(max_length=4000)),
                ('handle', models.CharField(blank=True, default='', max_length=90)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('notify', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=10)),
                ('pinned', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.Comment')),
            ],
            options={
                'verbose_name_plural': 'Replies',
                'ordering': ['rank', 'created_on'],
            },
        ),
    ]
