# Generated by Django 3.0.8 on 2021-02-23 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210222_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='name',
            new_name='username',
        ),
    ]
