# Generated by Django 3.0.8 on 2021-02-23 04:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210222_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agpost',
            name='sources',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='agpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.AGPost'),
        ),
    ]
