# Generated by Django 3.0.8 on 2021-03-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
