# Generated by Django 3.0.8 on 2021-03-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_reply_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='agpost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
